### PR TITLE
Update Huddle

### PR DESCRIPTION
**Pull request by richardowen**

### CODE REVIEW

**Comment by stroupaloop** [comment]
recommend using a different keyword besides FedRAMP since it's already on the page and indexed @richardowen

**Comment by richardowen** [comment]
@stroupaloop I have gone back (internally) to the person who wrote the update for an alternative keyword. Would you like me to submit another PR to remove/change the keyword if they come back to me or are we alright to leave as is (as I can see you have now merged the PR)? Thanks!

**Comment by stroupaloop** [comment]
It's fine as is but if you wanted to change out FedRAMP with a new keyword, that my increase visibility via search @richardowen

**Comment by richardowen** [comment]
Thanks, will feed that back

**Pull request merged**
